include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "test/**"
  errors:
    invalid_annotation_target: ignore
    invalid_use_of_internal_member: ignore
    unnecessary_null_comparison: ignore

linter:
  rules:
    # Организация импортов (временно отключено для снижения шума анализа)
    directives_ordering: false
    # Отключаем предупреждение о print в продакшене — используем логгер по мере рефакторинга
    avoid_print: false
    # Скобки в if/else — временно отключаем
    curly_braces_in_flow_control_structures: false
    # Отключаем const-подсказки (временная мера)
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    # Сортировка pub dependencies - отключаем из-за конфликтов с SDK зависимостями
    sort_pub_dependencies: false
    # Избегание ненужных контейнеров
    avoid_unnecessary_containers: true
    # Отключаем prefer_relative_imports так как проект использует абсолютные импорты
    prefer_relative_imports: false
