targets:
  $default:
    builders:
      # Отключаем drift_dev для AST моделей
      drift_dev:
        generate_for:
          exclude:
            - lib/scripts/**
      
      # Обеспечиваем работу freezed для AST моделей
      freezed:
        generate_for:
          include:
            - lib/**
      
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: lib/core/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/core/i18n
          output_file_name: strings.g.dart
          lazy: true
          locale_handling: true
          flutter_integration: true
          namespaces: true
          translate_var: t          
          translation_class_visibility: public
          key_case: camel
          key_map_case: camel
          param_case: camel
          string_interpolation: braces