name: part_catalog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.8.0+1
  drift: ^2.27.0  
  flutter_dotenv: ^5.2.1
  
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  logger: ^2.5.0
  collection: ^1.19.1  # Используйте последнюю совместимую версию
  equatable: ^2.0.7
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  pretty_dio_logger: ^1.4.0
  printing: ^5.14.2
  retrofit: ^4.4.2
  
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  slang: ^4.6.0
  slang_flutter: ^4.6.0
  sqlite3_flutter_libs: ^0.5.31
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.15
  drift_dev: ^2.27.0
  analyzer: ^7.3.0
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0
  json_serializable: ^6.9.4
  mockito: ^5.4.4
  mocktail: ^1.0.3
  retrofit_generator: ^9.1.9
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  slang_build_runner: ^4.6.0
  test: ^1.25.2

flutter:
  generate: true  # Включаем генерацию файлов локализации
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
