name: part_catalog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - .env
