name: part_catalog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  drift: ^2.25.1
  drift_dev: ^2.25.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  sqlite3_flutter_libs: ^0.5.31
  path: any
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  analyzer: ^7.3.0
  collection: ^1.19.1  # Используйте последнюю совместимую версию
  equatable: ^2.0.7
  uuid: ^4.5.1
  rxdart: ^0.28.0
  slang: ^4.6.0
  slang_flutter: ^4.6.0  
  go_router: ^15.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  slang_build_runner: ^4.6.0
  riverpod_generator: ^2.6.5

flutter:
  generate: true  # Включаем генерацию файлов локализации
  uses-material-design: true
  assets:
    - .env
